### ISSUE TITLE
Sync live/prod/app/main.tf to latest in terraform-aws-django

### ISSUE THREAD

**Issue by codyfletcher** [briancaffey/django-step-by-step#29]
I was having some trouble getting things to work out of the box. I _think_ this repo got out of sync with the terraform-aws-django repo (but I could totally be wrong).

Comparing [/terraform/live/prod/app/main.tf](https://github.com/briancaffey/django-step-by-step/blob/main/terraform/live/prod/app/main.tf) in this repo to the [example](https://github.com/briancaffey/terraform-aws-django/blob/main/examples/prod/app/main.tf) in the terraform-aws-django repo.

See [diff here](https://github.com/briancaffey/terraform-aws-django/commit/aa93862327aa4d5d1e8efd47112d23e7ae878ad5#diff-60659eac0dab6220156c1426d8ed1cfb0bb1ec2f4542e6735b10c7a13130b56b) from recent changes.

**Comment by briancaffey** [comment]
Hi @codyfletcher yes I think the `terraform-aws-django` library is ahead of what is being used in the `/terraform` directory of `django-step-by-step`. 

The `/examples` directory in `terraform-aws-django` is the last thing I tested. It is configured to use local state storage, so you don't need the S3 bucket or Dynamo table set up to use those, but you do need the ECR repos. Also, you need to have the `terraform.tfvars` file (examples/ad-hoc/base/terraform.tfvars) with the following: 

```
certificate_arn = "arn:aws:acm:us-east-1:111111111111:certificate/11111111-1111-1111-1111-fa8fa131d0e1"
domain_name     = "example.com"
```

using your certificate_arn and domain name.

**Comment by codyfletcher** [comment]
That definitely helps, thanks! My workflow was to use the latest in the main branch from django-step-by-step and terraform-aws-django, but it wasn't working. I thought I was doing something wrong but now I can rest a little easier. :D 

I've now got prod/base and prod/app working in GitHub Actions. 🎉

**Comment by briancaffey** [comment]
That's awesome! I'm not sure if I made this clear in the docs, but if you create a base name called `stage` (the default name), you need to use `stage` for the app stack as well (also the default name).

Make sure that the destroy operations work as well if you have not yet tried that!

**Comment by codyfletcher** [comment]
That totally perfect sense. I actually tore everything down and am building it all back up again. 

One thing I modified was adding `-var-file=$VAR_FILE` to `prod_base_destroy_terraform.yml`. 

**The error:**

```
var.domain_name
  Enter a value: Releasing state lock. This may take a few moments...
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 5:
│    5: variable "domain_name" {
```

**The change:**

```
terraform -chdir=terraform/live/prod/base \
  destroy \
  -auto-approve \
  -var-file=$VAR_FILE
```

**Comment by codyfletcher** [comment]
I think this is good now
